### ISSUE TITLE
Kewlr

### ISSUE THREAD

**Issue by kuraga** [zubuzon/kenra#1]
Good day, @zubuzon !

I saw your Kewlr NPM module. **Thanks for it very much! Your code is useful very much!**

But why have you removed it from Github? Could you restore it, please?

Thanks!

**Comment by zubuzon** [comment]
@kuraga  Hi. Sorry for late replies. I'm not a open source person and not so familiar with GH.  Plus my real life take all my time. Kewlr have never been on GH as far as i know. And it's was developed as an experiment too see how good performance i could gain.

If i find the source code on one of my computers i can push it.

**Comment by kuraga** [comment]
@zubuzon would be great, thanks very much!

**Comment by zubuzon** [comment]
@kuraga If the email address on your profile is valid, you should have got an email!
